services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3007:3007"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://admin:root@mongodb:27017/apinode?authSource=admin
    networks:
      - redeteste
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: node-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - dados_mongo:/data/db
    networks:
      - redeteste

networks:
  redeteste:
    driver: bridge

volumes:
  dados_mongo:
